### ISSUE TITLE
How install ?

### ISSUE THREAD

**Issue by timothylhuillier** [danwbyrne/HueSound#1]
Hi,

Can you help me for install your project in my computer (mac) ?

Thanks.

**Comment by danwbyrne** [comment]
Unfortunately I haven't had time to work on this project lately, it doesn't
work too well anyway this was just a place to keep track of any work I made
on it :/

**Comment by timothylhuillier** [comment]
Oki

I understand. I'm looking for to sync my music with my hue.
But I don't find :D only mobile app.

**Comment by danwbyrne** [comment]
If I make any more progress on it I will be sure to let you know.
